---
project:
  name: quickstart-nubeva-tlsdecrypt
  owner: erik@nubeva.com
  s3_regional_buckets: true
  shorten_stack_name: true
  s3_bucket: ''
  regions:
    - ap-northeast-1
    - ap-northeast-2
    # - ap-south-1
    - ap-southeast-1
    # - ap-southeast-2
    - eu-central-1
    # - eu-north-1
    - eu-west-2
    - eu-west-3
    - sa-east-1
    #- us-west-1
    - us-east-2
    - ca-central-1
tests:
  default:
   template: ./templates/nubeva-master.template.yaml
   parameters:
     AvailabilityZones: $[taskcat_genaz_2]
     APIKey: $[taskcat_genpass_10]
     RemoteAccessCIDR: "10.0.0.0/0"
     KeyPairName: $[taskcat_getkeypair]
     ToolAdmin: "tooladmin"
     ArkimeInstall: "false"
     NtopInstall: "true"
     WiresharkInstall: "true"
     SuricataInstall: "true"
     ZeekInstall: "true"
     ClientInstall: "true"
     AddESRole: "false"
     ToolPassword: $[taskcat_genpass_10]
     QSS3KeyPrefix: "quickstart-nubeva-tlsdecrypt/"
     QSS3BucketName: $[taskcat_autobucket]
     QSS3BucketRegion: $[taskcat_current_region]
  # existing-VPC:
  #   template: ./templates/nubeva-existing-vpc.template.yaml
  #   parameters:
  #     APIKey: "$[taskcat_genpass_10]"
  #     RemoteAccessCIDR: 10.0.0.0/0
  #     # KeyPairName: in .taskcat_overrides.yml
  #     ToolAdmin: tooladmin
  #     ArkimeInstall: "false"
  #     WiresharkInstall: "true"
  #     SuricataInstall: "false"
  #     ZeekInstall: "false"
  #     ClientInstall: "true"
  #     AddESRole: "false"
  #     ToolPassword: $[taskcat_genpass_10]
  #     QSS3KeyPrefix: quickstart-nubeva-tlsdecrypt/
  #     QSS3BucketName: $[taskcat_autobucket]
  #     QSS3BucketRegion: us-east-1
  #     # PrivateSubnet1ID: in .taskcat_overrides.yml
  #     # PrivateSubnet2ID: in .taskcat_overrides.yml
  #     # VPCID: in .taskcat_overrides.yml
