---
project:
  name: quickstart-nubeva-tlsdecrypt
  regions:
   - ap-northeast-1
   - ap-northeast-2
   - ap-south-1
   - ap-southeast-1
   - ap-southeast-2
   - eu-central-1
   - eu-north-1
   - eu-west-1
   - eu-west-2
   - eu-west-3
   - sa-east-1
     - us-east-1
   - us-west-1
   - us-east-2
   - us-west-2
   - ca-central-1
tests:
  default:
    template: ./templates/nubeva-master.template.yaml
    parameters:
      AvailabilityZones: "$[taskcat_genaz_2]"
      APIKey: "$[taskcat_genpass_10]"
      RemoteAccessCIDR: "10.0.0.0/0"
      KeyPairName: "$[taskcat_getkeypair]"
      ToolAdmin: "tooladmin"
      MolochInstall: "true"
      NtopInstall: "true"
      WiresharkInstall: "true"
      SuricataInstall: "true"
      ZeekInstall: "true"
      ClientInstall: "true"
      AddESRole: "false"
      ToolPassword: "$[taskcat_genpass_10]"
      QSS3KeyPrefix: "quickstart-nubeva-tlsdecrypt/"
      QSS3BucketName: "$[taskcat_autobucket]"
      QSS3BucketRegion: "us-east-1"
